version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: festa  # Criará o banco de dados "festa"
    ports:
      - "3306:3306"
    networks:
      - network-spring-mysql
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/festa
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - network-spring-mysql

networks:
  network-spring-mysql:
    driver: bridge
